# Generated by Django 4.2.2 on 2023-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=50)),
                ("Last_name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=20)),
                ("Re_Email", models.EmailField(max_length=20)),
                ("Batch", models.IntegerField()),
                ("password", models.CharField(max_length=40)),
                ("re_password", models.CharField(max_length=40)),
                ("textarea", models.CharField(max_length=50)),
                ("checkbox", models.CharField(max_length=50)),
                ("payments", models.DecimalField(decimal_places=2, max_digits=6)),
                ("django", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=50)),
                ("student_email", models.EmailField(max_length=35)),
                ("batch", models.IntegerField()),
                ("course", models.CharField(max_length=25)),
            ],
        ),
    ]
